language: elixir
elixir:
  - 1.5
  - 1.6
otp_release:
  - 19.1
  - 19.3
  - 20.3
  - 21.0
matrix:
  exclude:
    - otp_release: 19.1
      elixir: 1.6
    - otp_release: 19.3
      elixir: 1.6
    - otp_release: 21.0
      elixir: 1.5

services:
  - postgresql

addons:
  postgresql: "9.5"

cache:
  directories:
    - _build
    - deps

before_install:
  - wget -q https://binaries.cockroachdb.com/cockroach-v2.0.0.linux-amd64.tgz
  - tar xvf cockroach-v2.0.0.linux-amd64.tgz
  - cd cockroach-v2.0.0.linux-amd64 && nohup ./cockroach start --insecure --host=localhost &

before_script:
  - epmd -daemon
  - MIX_ENV=test mix compile --warnings-as-errors
  - MIX_ENV=test mix dialyzer --plt
  - cd cockroach-v2.0.0.linux-amd64 && ./cockroach sql --insecure --host=localhost --execute "create database postgres" && cd -
  - psql -c 'create database honeydew_test;' -U postgres

script:
  - mix test
  - cd examples/ecto_poll_queue/cockroachdb && MIX_ENV=test mix dialyzer --halt-exit-status && cd -
  - cd examples/ecto_poll_queue/postgres && MIX_ENV=test mix dialyzer --halt-exit-status && cd -
  - MIX_ENV=test mix dialyzer --halt-exit-status
