language: elixir
elixir:
  - 1.4.5
  - 1.5.1
otp_release:
  - 19.1
  - 19.3
  - 20.0
cache:
  directories:
    - _build
    - deps
before_script:
  - MIX_ENV=test mix compile --warnings-as-errors
script:
  - mix test
